apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: 1.0.1
    target:
      group: argoproj.io
      kind: Application
      name: geoserver
  - patch: |-
      - op: add
        path: /spec/source/helm/parameters[0]/name
        value: "ingress.hosts[0].host"
    target:
      group: argoproj.io
      kind: Application
      name: geoserver
  - patch: |-
      - op: add
        path: /spec/source/helm/parameters[0]/value
        value: "geoserverxyz.185-52-193-246.nip.io"
    target:
      group: argoproj.io
      kind: Application
      name: geoserver
  - patch: |-
      - op: add
        path: /spec/source/helm/parameters[1]/name
        value: "ingress.tls[0].hosts[0]"
    target:
      group: argoproj.io
      kind: Application
      name: geoserver
  - patch: |-
      - op: add
        path: /spec/source/helm/parameters[1]/value
        value: "geoserverxyz.185-52-193-246.nip.io"
    target:
      group: argoproj.io
      kind: Application
      name: geoserver
