apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: argoproj.io
      kind: Application
      name: geoserver
    patch: |-
      - op: add
        path: /spec/source/targetRevision
        value: 1.0.1
      - op: add
        path: /spec/source/helm/parameters
        value:
          - name: "ingress.hosts[0].host"
            value: geoserver123.185-52-193-246.nip.io
          - name: "ingress.tls[0].hosts[0]"
            value: geoserver123.185-52-193-246.nip.io
