apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: 1.0.1
    target:
      group: argoproj.io
      kind: Application
      name: geoserver
