apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Inherit from base
bases:
  - ../../base
# Just override (patch) a few deployment-specific values
patchesStrategicMerge:
- |-
  apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: geoserver
    namespace: argocd
  spec:
    project: default
    source:
      targetRevision: 1.0.1
      helm:
        parameters:
          - name: "ingress.hosts[0].host"
            value: geoserver.dsp3.185-52-193-246.nip.io
          - name: "ingress.tls[0].hosts[0]"
            value: geoserver.dsp3.185-52-193-246.nip.io
