#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
  rm -f cluster.yml
}
trap onExit EXIT

main() {
  rke_config
  rke up
}

rke_config() {
  cat - <<EOF >cluster.yml
cluster_name: qctools
kubernetes_version: "v1.22.11-rancher1-1"
nodes:
  - address: 172.26.59.13
    user: rke
    role:
      - controlplane
      - etcd
      - worker
  # - address: 172.26.59.10
  #   user: rke
  #   role:
  #     - worker
  # - address: 172.26.59.11
  #   user: rke
  #   role:
  #     - worker
  # - address: 172.26.59.12
  #   user: rke
  #   role:
  #     - worker

ingress:
  provider: none
EOF
}

main "$@"
