#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

cat - <<EOF
DO NOT use the metallb load-balancer as it does not play nicely with the TPZ-UK VM network
It is not needed as the 'externalIP' of the ingress-nginx is set directly
Aborting...
EOF
exit 1

# export LB_ADDRESSES="${LB_ADDRESSES:-$(minikube ip)/32}"
export LB_ADDRESSES="172.26.59.13/32"

# install metallb
helm upgrade -i metallb metallb \
  --repo https://metallb.github.io/metallb \
  --namespace metallb-system --create-namespace

# configure address pool
# we have to wait for the controller to be ready for this...
while [ $(kubectl -n metallb-system get deploy/metallb-controller -ojson | jq -r '.status.readyReplicas // 0') -lt 1 ]; do
  echo "Wating for loadbalancer readiness..."
  sleep 5
done
# ...now we can proceed
cat - <<EOF | kubectl apply -f -
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: qctool-pool
  namespace: metallb-system
spec:
  addresses:
    - ${LB_ADDRESSES}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: qctool-loadbalancer
  namespace: metallb-system
spec:
  ipAddressPools:
    - qctool-pool
EOF
