#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

# install metallb
helm install metallb metallb \
  --repo https://metallb.github.io/metallb \
  --namespace metallb-system --create-namespace

# configure address pool
# we have to wait for the controller to be ready for this...
while [ $(kubectl -n metallb-system get deploy/metallb-controller -ojson | jq -r .status.readyReplicas) != 1 ]; do
  echo "Wating for loadbalancer readiness..."
  sleep 5
done
# ...now we can proceed
cat - <<EOF | kubectl apply -f -
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: minikube-pool
  namespace: metallb-system
spec:
  addresses:
    - $(minikube ip)/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: minikube-loadbalancer
  namespace: metallb-system
spec:
  ipAddressPools:
    - minikube-pool
EOF
