#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

# ensure that env GITHUB_USER and GITHUB_TOKEN are exported

flux bootstrap github \
  --owner="${GITHUB_USER}" \
  --repository="eoepca-flux" \
  --branch="main" \
  --private=false \
  --personal=true \
  --path="deploy"
