#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

export GITHUB_REPO="${GITHUB_REPO:-QC-Tool-Suite-eoepca}"
export GITHUB_BRANCH="${GITHUB_BRANCH:-main}"
export GITHUB_PATH="${GITHUB_PATH:-deploy}"

flux bootstrap github \
  --token-auth \
  --owner="Telespazio-UK" \
  --repository="${GITHUB_REPO}" \
  --branch="${GITHUB_BRANCH}" \
  --path="${GITHUB_PATH}"
