---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 2m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: nfs-provisioner
spec:
  # suspend: true
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.12
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs-provisioner
  values:
    provisionerName: nfs-storage
    storageClass:
      name: managed-nfs-storage
      create: true
      reclaimPolicy: Delete
      archiveOnDelete: false
      allowVolumeExpansion: true
    nfs:
      server: "172.26.59.13"
      path: /data/dynamic
  interval: 1m0s
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: nfs-provisioner-retain
#   namespace: nfs-provisioner
# spec:
#   suspend: true
#   chart:
#     spec:
#       chart: nfs-subdir-external-provisioner
#       version: 4.0.12
#       sourceRef:
#         kind: HelmRepository
#         name: nfs-subdir-external-provisioner
#         namespace: nfs-provisioner
#   values:
#     provisionerName: nfs-storage-retain
#     storageClass:
#       name: managed-nfs-storage-retain
#       create: true
#       reclaimPolicy: Retain
#       allowVolumeExpansion: true
#     nfs:
#       server: "172.26.59.13"
#       path: /data/dynamic
#   interval: 1m0s
