apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: resource-catalogue-guard
  namespace: rm
spec:
  chart:
    spec:
      chart: resource-guard
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    #---------------------------------------------------------------------------
    # Global values
    #---------------------------------------------------------------------------
    global:
      context: resource-catalogue
      domain: 185-52-193-246.nip.io
      nginxIp: 185.52.193.246
      # certManager:
      #   clusterIssuer: letsencrypt
    #---------------------------------------------------------------------------
    # PEP values
    #---------------------------------------------------------------------------
    pep-engine:
      configMap:
        asHostname: auth
        pdpHostname: auth
        # limitUses: 100
      nginxIntegration:
        enabled: false
        # hostname: combined-rm-auth
      # image:
      #   pullPolicy: Always
      volumeClaim:
        name: eoepca-resman-pvc
        create: false
    #---------------------------------------------------------------------------
    # UMA User Agent values
    #---------------------------------------------------------------------------
    uma-user-agent:
      # image:
      #   tag: latest
      #   pullPolicy: Always
      nginxIntegration:
        enabled: true
        hosts:
          - host: 185-52-193-246.nip.io
            paths:
              - path: /resource-catalogue/(.*)
                pathType: Prefix
                service:
                  name: resource-catalogue-service
                  port: 80
              - path: /resource-catalogue$
                pathType: Exact
                service:
                  name: resource-catalogue-service
                  port: 80
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/rewrite-target: /$1
          nginx.ingress.kubernetes.io/configuration-snippet-zzz: |
            rewrite ^(/resource-catalogue)$ $1/ redirect;
      client:
        credentialsSecretName: "resman-client"
      logging:
        level: "info"
      unauthorizedResponse: 'Bearer realm="https://portal.185-52-193-246.nip.io/oidc/authenticate/"'
      openAccess: true
    #---------------------------------------------------------------------------
    # END values
    #---------------------------------------------------------------------------

  timeout: 25m0s
  interval: 1m0s
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: resman-client
  namespace: rm
data:
  client.yaml: Y2xpZW50LWlkOiBkdW1teS1jbGllbnQtaWQKY2xpZW50LXNlY3JldDogZHVtbXktY2xpZW50LXNlY3JldA==
