apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: proc-ades
  namespace: proc
spec:
  chart:
    spec:
      chart: ades
      version: 2.0.24
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    # values - start
    image:
      pullPolicy: Always
    workflowExecutor:
      stagein:
        cwl: |
          cwlVersion: v1.0
          doc: "Run Stars for staging input data"
          class: CommandLineTool
          hints:
            DockerRequirement:
              dockerPull: gr4n0t4/stagein:0.0.1
            "cwltool:Secrets":
              secrets:
              - ADES_STAGEIN_AWS_SERVICEURL
              - ADES_STAGEIN_AWS_ACCESS_KEY_ID
              - ADES_STAGEIN_AWS_SECRET_ACCESS_KEY
          id: stars
          inputs:
            ADES_STAGEIN_AWS_SERVICEURL:
              type: string?
            ADES_STAGEIN_AWS_ACCESS_KEY_ID:
              type: string?
            ADES_STAGEIN_AWS_SECRET_ACCESS_KEY:
              type: string?
          outputs: {}
          baseCommand: ['/bin/bash', 'stagein.sh']
          requirements:
            InitialWorkDirRequirement:
              listing:
              - entryname: stagein.sh
                entry: |-
                  #!/bin/bash
                  export AWS__ServiceURL=$(inputs.ADES_STAGEIN_AWS_SERVICEURL)
                  export AWS_ACCESS_KEY_ID=$(inputs.ADES_STAGEIN_AWS_ACCESS_KEY_ID)
                  export AWS_SECRET_ACCESS_KEY=$(inputs.ADES_STAGEIN_AWS_SECRET_ACCESS_KEY)
                  url=$1
                  if curl --output /dev/null --silent --head --fail "$url"; then
                    echo "URL: $url"
                  else
                    echo "URL does not exist: $url"
                    exit 1
                  fi
                  python /run.py $url
            EnvVarRequirement:
              envDef:
                PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            ResourceRequirement: {}

      inputs:
        # stage-in
        STAGEIN_AWS_SERVICEURL: http://minio.172-26-59-13.nip.io
        STAGEIN_AWS_ACCESS_KEY_ID: eoepca
        STAGEIN_AWS_SECRET_ACCESS_KEY: changeme
        STAGEIN_AWS_REGION: us-east-1
        # stage-out
        STAGEOUT_AWS_SERVICEURL: http://minio.172-26-59-13.nip.io
        STAGEOUT_AWS_ACCESS_KEY_ID: eoepca
        STAGEOUT_AWS_SECRET_ACCESS_KEY: changeme
        STAGEOUT_AWS_REGION: us-east-1
        STAGEOUT_OUTPUT: s3://eoepca
      # Workspace integration
      useResourceManager: false
      resourceManagerWorkspacePrefix: "qctool"
      resourceManagerEndpoint: "https://workspace-api.172-26-59-13.nip.io"
      platformDomain: "https://auth.172-26-59-13.nip.io"
      # Kubernetes storage
      processingStorageClass: managed-nfs-storage
      # Size of the Kubernetes Tmp Volumes
      processingVolumeTmpSize: "6Gi"
      # Size of the Kubernetes Output Volumes
      processingVolumeOutputSize: "6Gi"
      # Max ram to use for a job
      processingMaxRam: "12Gi"
      # Max number of CPU cores to use concurrently for a job
      processingMaxCores: "4"
    wps:
      pepBaseUrl: "http://ades-pep:5576"
      usePep: false
    persistence:
      storageClass: managed-nfs-storage-retain
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        # nginx.ingress.kubernetes.io/use-regex: "true"
        # nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        # nginx.ingress.kubernetes.io/rewrite-target: /$1
      hosts:
        - host: ades-open.172-26-59-13.nip.io
          paths: 
            - path: /
              pathType: ImplementationSpecific
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local
    # values - end
  interval: 1m0s
