---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: harbor
  namespace: rm
spec:
  interval: 2m
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: 1.11.1
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: rm
  values:
    expose:
      ingress:
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
          # from chart:
          ingress.kubernetes.io/ssl-redirect: "false"
          ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          core: harbor.172-26-59-13.nip.io
      tls:
        enabled: false
        certSource: secret
        secret:
          secretName: "harbor-tls"

    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: managed-nfs-storage-retain
        chartmuseum:
          storageClass: managed-nfs-storage-retain
        jobservice:
          storageClass: managed-nfs-storage-retain
        database:
          storageClass: managed-nfs-storage-retain
        redis:
          storageClass: managed-nfs-storage-retain
        trivy:
          storageClass: managed-nfs-storage-retain

    externalURL: http://harbor.172-26-59-13.nip.io
    # initial password for logging in with user "admin"
    # harborAdminPassword: "Harbor12345"  # this is the default in the helm chart

    chartmuseum:
      enabled: false
    trivy:
      enabled: false
    notary:
      enabled: false
