---
apiVersion: v1
kind: Namespace
metadata:
  name: clients
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonstrator-site
  namespace: clients
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
        - name: demonstrator-site
          image: qctool-demonstrator
          imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: demonstrator-site
  namespace: clients
spec:
  type: NodePort
  selector:
    bb: web
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demonstrator-site
  namespace: clients
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: demonstrator.172-26-59-13.nip.io
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: demonstrator-site
            port:
              number: 80