---
apiVersion: v1
kind: Namespace
metadata:
  name: clients
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonstrator-site
  namespace: clients
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
        - name: demonstrator-site
          image: qctool-demonstrator
          imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: demonstrator-site
  namespace: clients
spec:
  type: NodePort
  selector:
    bb: web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
