apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 010-ingress-nginx.yaml
  - 015-minio.yaml
  - 020-namespaces.yaml
  - 030-helm-repositories.yaml
  # - 040-nfs-provisioner.yaml
  - 050-storage-volumes.yaml
  # - 060-rm-client-secret.yaml
  - 070-resource-catalogue.yaml
  # - 075-resource-catalogue-guard.yaml
  # - 080-data-access.yaml
  # - 085-data-access-guard.yaml
  - 090-ades.yaml
