apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: resource-catalogue
  namespace: rm
spec:
  interval: 5m 
  chart:
    spec:
      chart: rm-resource-catalogue
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    global:
      namespace: rm
    ingress:
      enabled: true
      name: resource-catalogue
      host: resource-catalogue.192.168.49.2.nip.io
      # we're not using tls, but the resource-catalogue helm chart insists on
      # having values anyway - so may as well set consistent values
      tls_host: resource-catalogue.192.168.49.2.nip.io
      tls_secret_name: resource-catalogue-tls
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    db:
      volume_storage_type: standard
    pycsw:
      config:
        server:
          url: http://resource-catalogue.192.168.49.2.nip.io/
